### ISSUE TITLE
Create interactive Bots to engage users and answer their questions

### ISSUE THREAD

**Issue by kbavandi** [techforwarren/start-here#5]
Just for disclosure, I am promoting some of the tools I have developed and the examples are to shed light on what is possible. Everything can be customized.

Our tools make it easy to curate digital links, comment on them, tag them and publish them into a content library.

My idea is simple. Let's curate all of Warren's posts on Social Media and her comments, organize and categorize them, then use Google's DiagFlow platform (This is an AI-based natural language processing Solution) to create interactive charts to both educate and answer voter questions in context! 

I have been curating news on the Trump Presidency for 3 years. I have used my research an applied it to the concept above. I am making a couple of modifications to make the experience even better, but you can see the application from my example.

My chat example has answered a few questions on the Trump presidency to demonstrate the power of our solution.

[Click here ](https://optimalaccess.com/content-curation-service/)and the chat will appear at the bottom right corner of the page.

**Comment by john-osullivan** [comment]
Super cool premise!  I guess the next step here would be gathering and tagging the source data, yeah?  What sort of tags do you think make sense?

**Comment by kbavandi** [comment]
I usually assign two types of tags. Micro and Macro.
Micro tags define the content of the post, like the economy, global warming, jobs, etc.
Macro tags are there to promote certain ideas. For example, in Trump's case, he made some "[Campaign Promises](https://www.kbucket.com/eontransform/us-politics-2016/us-elections/election-2016/?kbtag=campaign+promises)", or has conducted himself in ways that present a "[Conflict of Interest](https://www.kbucket.com/eontransform/us-politics-2016/us-elections/election-2016/?kbtag=conflict+of+interest)".

The program has two-tier filtering, so once you pick "Conflict of Interest" for example, you can pick "[Jared Kushner](https://www.kbucket.com/eontransform/us-politics-2016/us-elections/election-2016/?kbtag=conflict+of+interest&rtag=jared+kushner)" to get more specific.

We can add additional layers, which I think will be useful. When using this tagging in conjunction with the Bot, we will be able to answer very specific questions.

Our tools make it very easy to modify the tags and optimize the response.

**Comment by Hucxley** [comment]
FYI we have a Reddit bot in progress that responds to requests for Sen. Warren's plans with the summary from her issues website and a link to the detailed articles on Medium.  I still don't know how I feel about aggregating content (thank you for your disclosure), mainly because I haven't seen it in action for the positive things about Sen. Warren's campaign.  Anyone can run a campaign on what everyone else does wrong, but can we aggregate content based on what Sen. Warren does right?

If there was a demo focused on the positives of Sen. Warren's campaign, I could probably get behind this more.  But, as it is, we have volunteers working right now on spreading information about Sen. Warren's campaign, policies, and plans, with community-built tools and intend to keep expanding our WarrenPlan bots to other platforms once our Reddit bot has had some room to breathe.

I feel like we're splitting effort, but I'm not sure if the aggregate bot's audience is voters or Warren campaign administrators.

**Comment by kbavandi** [comment]
As a demo I curated tweets from different Democrats presidential candidates and here is [Warren's filter](https://www.kbucket.com/eontransform/progressives/tweet-library/progressive-tweets/?atag=Elizabeth+Warren). Every tweet she puts out (She has on average 10 a day) is a policy position. By curating and properly tagging all her tweets and Facebook posts, we can create a powerful Bot that will answer voter questions in a powerful way.

These Bots can be deployed on her website, on Facebook, Twitter, slack, phone messages and a few other platforms.

The analytics on the Bots will help the campaign learn from user questions and build new dialogs that specifically answer voter concerns.

In my experience, and I have dedicated my career to indexing content, a proper flexible indexing platform is essential to the success of such an application.

Do you have a link to the Reddit Bot?

**Comment by Hucxley** [comment]
The Reddit bot is currently in manual mode while we test it and map the
policy keywords at https://reddit.com/r/WPBSandbox

**Comment by kbavandi** [comment]
Thanks, Hucxley. First have your tried DiagFlow. The platform is awsome and free and all the chat functionality is built-in (with voice activation). Additionally, whatever we program there will appear in Google Search which will scale even better.

An index into the content will really help design better and more informative conversations. I will create a Warren KBucket and add some of the Medium posts in there to test it out.

**Comment by Hucxley** [comment]
I haven't tried DiagFlow, but I will when I get some spare time.

**Comment by kbavandi** [comment]
Ok Guys, check this out and let me know what you think. The branding on the page will go away and we should be able to just launch the bot (hopefully by next week). 

These bots can be sent as mobile messages.

https://optimalaccess.com/ewarren/

**Comment by Hucxley** [comment]
So, we have two people working like crazy to build bots for Warren's plans,
and them we have this division of work, again.

On one side, open source, community-built, on the other, opaque and
inaccessible by the rest of us in the community.

I know it must feel like I have nothing better to do than criticize your
efforts, but the two of us are working on a similar project, and it seems
to be potentially confusing to everyone else.

Community: Do we need to help with bots? Nah, we got a bot. Us: But the bot
is a commercial product that has the same problem as the community bot did
a week ago. Community: I'm confused, so I'll wait and see what happens.

Why do we have two groups working on the same thing in totally different
directions?

**Comment by shaisachs** [comment]
Hi there, I don't think we necessarily need to choose between one and the other. Or perhaps in emoji form, :whynotboth:?

It's also not entirely clear to me that the two bots are doing exactly the same thing - one appears to be a Reddit bot (perhaps one that could be expanded to other forums / Slack / etc.), and the other seems to be a standalone web app. They are certainly similar in format but still distinct in functionality - or am I missing something?

Put another way - if need be we can have two different but similar projects, there's no real harm in that. Does that make sense or is it not really possible?

**Comment by Hucxley** [comment]
The background is the other bot is from a company that introduced itself by
promoting their company's tool. Their platform is not just for Elizabeth
Warren, but is based on what they choose to aggregate into it's content
engine. It's not open source. None of us know what it's doing, what it's
tracking, or who is behind it. And they've resisted, time and time again,
to strip their bot of self-promoting opportunities. Even the most recent
demo needs some "wrappers" removed, which the poster claims they will soon
do.

It feels to me like they have been, and still are, trying to find a way to
get their commercial product close enough to the campaign to possibly make
a sale.

To me, this volunteer community's purpose is not sell things to the
campaign, but to try to help the candidate we support win.

I tried their bot demo today, and it literally does the same thing ours
does, only they have fewer plans in their library than the current Reddit
bot. The only difference is  Instead of helping us get the Reddit bot to do
better language processing, they're just using their standard product
wrapper and tagging articles so they respond to Warren queries.

We're building ours from the ground up, reaching out to different groups
that support Sen Warren to try to get permission to deploy the bought we've
built from scratch, and this company's representative can walk in and
confuse those conversations and relationships we're building by talking
about their bot that seemingly does the same thing ours does.

I'd be able to be more open minded about this if the person who keeps
posting about it actually contributed anything other than using us to try
and get closer to the campaign leadership.

Look at our tests we're running on https://www.reddit.com/r/WPBSandbox and
the demo they posted today. You tell me if what they're doing is different
than what we've been working on for two weeks now other than the interface.

If the other person posting their bot cared about the community, why
haven't they joined our project? Or, if our project was making progress
without them, why haven't they offered to contribute to anything else?
Their agenda is clear - promote their bot and try to get traction with it.

I'm sorry if I take a bit of slight when there's a company trying to come
into our community and trample over something that I have built for the
community with community members, working sometimes until midnight or
later, or getting up at 4 in the morning and working on before getting
ready to go to work. And this other person, promoting their bot, has not
offered to lift a finger to help so we don't have to be the only two
carrying the load.  Instead, they just keep posting about their product,
and asking me if I've read about DiagFlow from Google.

I'm going to keep working on the project that Joe and I have been working
on. If people can't see that we should be working collaboratively to build
tech to support Warren in an efficient and productive way, then I don't
know what to say about that.

And, yes, we'd like to expand to other platforms, but until we get our language processing and matching algorithms dialed in to actually answer queries with the correct policy plan proposal, we're not going to start trying to do other platforms.

**Comment by kbavandi** [comment]
First a respond to @Hucxley. We had one conversation, you stated your concern about me promoting my own tools, and I was clear then, as I was in my opening here that yes, these are my tools, I think that the Warren camp should be using them, and I also want the community to be aware of them.

I also asked you to not miss the forest for the trees. I am here because Warren's campaign resonates with me and I believe I can offer tools that can help her with messaging and communication. I am not trying to compete with you or negate your work.

There is nothing hidden about what we do. Actually, curation is all about transparency. All I have done is to curate some of EW's medium and twitter posts tagged them by topic and organized them [on this page.](https://www.kbucket.com/eontransform/elizabeth-warren/elizabeth-warren/elizabeth-warren/).

Next, I am using Google's DiagFlow platform, to create conversations that help people understand her position, in context! Then I use another solution by a partner (BotCopy) to embed the bots on the website.

Our content hubs (KBucket) make it easy to build conversations quickly and link to multiple answers around a topic like corruption, gun control, climate change, etc.

The goal should be to take every post (Blog, YouTube, Twitter, Facebook, Instagram), organize and categorize it and then build specific intents that answer voter questions.

So now every content that is automatically added to the bot (if the category already exists).

The advantage of the DiagFlow platform is that it can be deployed on multiple platforms and messaging systems.

So answer to your question dear @NGPVAN, yes why not both. I am here to present my solutions and help in any way I can.

**Comment by shaisachs** [comment]
Hi there - if we could, let's please dial back the temperature a little. We're a volunteer-run group with commensurate time and no actual budget to speak of - everyone here is giving of their time and enthusiasm, which is certainly appreciated.

You all are certainly free to work on whatever projects you see fit and which fit your skill levels, indeed that'd be the case even if the group didn't exist at all. If there happen to be two projects doing largely similar things, there's nothing wrong with that as such. That said - while we haven't really discussed software licensing properly, all of our repositories are public so it's reasonable to expect that the code is likely to be open source in some fashion or other. (My vote is for MIT license but, separate discussion.) So to the degree that you want to share code with the community, and likewise gather fellow developers to help out, at some point or another your code is going to have to be public - see for example some of the great work that is being done in the [eventmap repo](https://github.com/techforwarren/eventmap).

I don't think there's anything wrong with discussing commercial/proprietary solutions as such, but I do think that promotions of your own products should be clearly labeled as such. Also, for what it's worth, there's really only so far such promotions go, since this group is volunteer-run and doesn't have any budget to speak of - we don't have any authority or means for procurement.

Finally I should make clear: while I used to work at NGP VAN, I don't any more, and haven't for several months. Nothing I do or say here is at all related to what they're doing. Though I'm sure whatever it is, is fine work.

**Comment by Hucxley** [comment]
Thank you, and I agree. I also take responsibility for not letting things
go and minding my business a long time ago. While it's reasonable to be
passionate about what we're doing here, it is unacceptable to insert
toxicity into the group, which I've done.

So, I will dial it all the way back. I will try to learn from the other
members of the community, and since it was recommended to me to check out
DiagFlow, I will. Maybe it will help us with processing incoming queries
without reinventing the wheel.

Since I'm responsible for continuing to make an issue where there shouldn't
be one, I will make a concerted effort to be supportive and positive where
I haven't been.

Thank you for your patience in this bit of a rocky start on my behalf.

**Comment by shaisachs** [comment]
Thanks so much, I really appreciate your participation so far. I know these things can sometimes be tricky, especially in early days. Even so the progress we've made so far with bots is amazing!

**Comment by kbavandi** [comment]
Thank you for all the honest dialog. I am working on twitter integration. Hope to share an example soon.
