### ISSUE TITLE
Medicare for All cost calculator

### ISSUE THREAD

**Issue by IsambardBrunel** [techforwarren/start-here#9]
I would like to see a M4A cost calculator site/app into which people can input some basic information about their circumstances and current plan and get an estimate of cost savings under M4A.

The site should be able to create a basic monthly cost calculation based on premiums and should also be able to generate some scenarios that explain common "what if" situations. What-ifs might include:

1. Child birth
2. Emergency situation - e.g. car accident
3. Common chronic condition - e.g. diabetes 

By registering the user would be able to save a scenario and , with their permission we would be able to use their contact details for communication and their anonymized scenario details for analytics.

The user should be able to sign up for news on the campaign and specific to healthcare.

**Comment by shaisachs** [comment]
That is an awesome idea! Do you know if someone has already done some of the math on this? It could work out really nicely in concert with the microsites project, which (hopefully) will have stuff like a signup form built-in.

**Comment by IsambardBrunel** [comment]
I suspect that the math would involve piecing some data together from the Medicare for All bill, the IRS and possibly some study of the plans on the healthcare.gov site. This would not be trivial but it could be enjoyable research.

**Comment by danielnarey** [comment]
Thanks for sharing your proposal @IsambardBrunel . Since this is a project that requires detailed (and complex) policy analysis, we would need someone to take on that policy analysis and write up some kind of brief that could be reviewed by other policy experts before we could consider building any tech around it. There are some other projects in the works like [policyboard](https://github.com/techforwarren/policyboard) to help folks parse the details of Warren’s policy proposals, so that might be a good place to start for anyone interested in M4A.
